In [4]:
# !pip install beautifulsoup4 pandas lxml

Requirement already satisfied: beautifulsoup4 in c:\users\user\anaconda3\lib\site-packages (4.12.2)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: lxml in c:\users\user\anaconda3\lib\site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\user\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [11]:
import pandas as pd
from bs4 import BeautifulSoup

# HTML 파일 열기
with open("프로야구순위_24-08-22.html", "r", encoding="utf-8") as file:
    html_content = file.read()

# BeautifulSoup으로 HTML 파싱
soup = BeautifulSoup(html_content, 'html.parser')

# 테이블 찾기: class가 'tb_type2'인 테이블을 선택
table = soup.find("table", class_="tb_type2")

# 테이블의 행 데이터 추출
rows = []
for row in table.find_all("tr"):
    columns = row.find_all(["th", "td"])  # th(헤더)와 td(데이터)를 모두 포함
    if columns:  # 빈 행 제외
        rows.append([col.get_text(strip=True) for col in columns])

# pandas DataFrame으로 변환 (헤더가 따로 없는 경우 자동으로 열 이름을 부여)
df = pd.DataFrame(rows)

# DataFrame 출력
df

     0    1    2   3  4   5      6     7   8         9
0   순위   팀명   경기   승  무   패     승률   게임차  연속    최근10경기
1    1  KIA  117  69  2  46  0.600   0.0  5승  7승-3패-0무
2    2   삼성  119  64  2  53  0.547   6.0  1패  7승-3패-0무
3    3   LG  116  61  2  53  0.535   7.5  1패  5승-5패-0무
4    4   두산  121  62  2  57  0.521   9.0  1승  6승-4패-0무
5    5  SSG  117  57  1  59  0.491  12.5  1승  4승-6패-0무
6    6   KT  118  56  2  60  0.483  13.5  1승  3승-7패-0무
7    7   한화  115  53  2  60  0.469  15.0  1패  5승-5패-0무
8    8   롯데  111  50  3  58  0.463  15.5  1패  6승-4패-0무
9    9   NC  114  50  2  62  0.446  17.5  1승  1승-9패-0무
10  10   키움  116  51  0  65  0.440  18.5  1패  5승-5패-0무

In [9]:
import pandas as pd
from bs4 import BeautifulSoup

# HTML 파일 읽기
with open('프로야구순위_24-08-22.html', 'r', encoding='utf-8') as file:
    html_content = file.read()

# BeautifulSoup 객체 생성
soup = BeautifulSoup(html_content, 'html.parser')

# 특정 테이블 추출 (id가 teamRankTabPanel_0인 부분에서 첫 번째 테이블을 찾습니다)
table = soup.find('div', {'id': 'teamRankTabPanel_0'}).find('table')

# 테이블에서 데이터를 추출하여 데이터프레임으로 변환
df = pd.read_html(str(table))[0]

# 데이터프레임 출력
df

C:\Users\user\AppData\Local\Temp\ipykernel_1096\2797909951.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   순위   팀명   경기   승  무   패     승률   게임차  연속    최근10경기
0   1  KIA  117  69  2  46  0.600   0.0  5승  7승-3패-0무
1   2   삼성  119  64  2  53  0.547   6.0  1패  7승-3패-0무
2   3   LG  116  61  2  53  0.535   7.5  1패  5승-5패-0무
3   4   두산  121  62  2  57  0.521   9.0  1승  6승-4패-0무
4   5  SSG  117  57  1  59  0.491  12.5  1승  4승-6패-0무
5   6   KT  118  56  2  60  0.483  13.5  1승  3승-7패-0무
6   7   한화  115  53  2  60  0.469  15.0  1패  5승-5패-0무
7   8   롯데  111  50  3  58  0.463  15.5  1패  6승-4패-0무
8   9   NC  114  50  2  62  0.446  17.5  1승  1승-9패-0무
9  10   키움  116  51  0  65  0.440  18.5  1패  5승-5패-0무